### ISSUE TITLE
多样例判题

### ISSUE THREAD

**Issue by J-Smile** [kk-OJ/code-judge#1]
如果有多个样例需要走判题，能不能加一下相关的功能呀，谢谢，洛谷使用的 Testlib 库这个，我对于cpp不是很懂，麻烦了

**Comment by zyyzyykk** [comment]
你好，首先**感谢**你的支持与鼓励

对于判题功能我的规划是这样的：
如果每次判题的正确输出都要作为请求参数的话，将极大消耗网络资源。我的想法是将题目的正确输出先传到这个判题机上面（管理员创建题目时）作为文件，然后在判题时直接进行一般或特殊的对比。
因此，判题可能需要先实现一些文件上传的接口，需要与后端（未进行开发）进行配合。

最近我的时间比较紧张，暂时不会开发这个OJ项目的前后端，我对此感到抱歉

不过我已经将 **执行代码并获取结果** 这个核心方法开发完毕，你要做的只是将输出结果与答案进行比较即可
